In [142]:

from sklearn import preprocessing
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
dataset=pd.read_csv('gender-prediction.csv')

dataset






height  weight beard hair_length  shoe_size scarf eye_color  gender
0       71     176   yes       short         44    no     black    male
1       68     165    no        bald         41    no     black    male
2       62     132    no      medium         37   yes      blue  female
3       65     138    no        long         38    no      gray  female
4       70     197   yes      medium         43    no      gray    male
..     ...     ...   ...         ...        ...   ...       ...     ...
80      61     103    no        long         36   yes     brown  female
81      72     176   yes       short         40    no     brown    male
82      65     134    no      medium         42    no     black  female
83      61     122    no        long         32   yes     black  female
84      68     150   yes       short         32    no     black    male

[85 rows x 8 columns]

In [143]:
#retrived=dataset[['height','weight','beard','hair_length','scarf','gender']]
#retrived


In [144]:


X=dataset.drop(['gender'],axis=1)
Y=dataset['gender']
Y


#X=retrived.drop('gender',axis=1)
#Y=retrived['gender']
#X

0       male
1       male
2     female
3     female
4       male
       ...  
80    female
81      male
82    female
83    female
84      male
Name: gender, Length: 85, dtype: object

In [145]:
labels = preprocessing.LabelEncoder()
Y = labels.fit_transform(Y)
print(Y)

[1 1 0 0 1 1 1 1 0 0 0 1 1 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 0 1 0
 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 0 1 0 1 1 0
 0 0 0 1 1 0 0 1 0 0 1]


In [146]:
#convert categorical columns into numeric values
#for beard
X['beard'].replace(['no','yes'],[0,1],inplace=True)

#for hair_length
X['hair_length'].replace(['bald','short','medium','long'],[0,1,2,3],inplace=True)


#for scarf
X['scarf'].replace(['no','yes'],[0,1],inplace=True)

#for eye_color

X['eye_color'].replace(['black','blue','gray','brown','green'],[0,1,2,3,4],inplace=True)
 
X


height  weight  beard  hair_length  shoe_size  scarf  eye_color
0       71     176      1            1         44      0          0
1       68     165      0            0         41      0          0
2       62     132      0            2         37      1          1
3       65     138      0            3         38      0          2
4       70     197      1            2         43      0          2
..     ...     ...    ...          ...        ...    ...        ...
80      61     103      0            3         36      1          3
81      72     176      1            1         40      0          3
82      65     134      0            2         42      0          0
83      61     122      0            3         32      1          0
84      68     150      1            1         32      0          0

[85 rows x 7 columns]

In [147]:
#X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.33,random_state=6,)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=6,)


In [126]:

# Ranndon  forest

from sklearn.ensemble import RandomForestClassifier
classifyRF=RandomForestClassifier()
classifyRF.fit(X_train,Y_train)
y_predictRF=classifyRF.predict(X_test)

In [127]:
# Multilayer preceptron
from sklearn.neural_network import MLPClassifier
classifyMLP = MLPClassifier()
classifyMLP.fit(X_train,Y_train)
y_predictMLP=classifyMLP.predict(X_test)


C:\python\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [128]:




#Support vector machine
from sklearn import svm
classifysvm = svm.SVC()
classifysvm.fit(X_train,Y_train)
y_predictsvm=classifysvm.predict(X_test)


In [129]:
Y_test

array([0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0])

In [130]:
#accuracy of random forest
from sklearn import metrics
from sklearn.metrics import accuracy_score 
RandomForest= accuracy_score(Y_test, y_predictRF)
print("Accuracy of Random Forest is",RandomForest*100)
print(metrics.confusion_matrix(Y_test, y_predictRF))



Accuracy of Random Forest is 93.75
[[7 1]
 [0 8]]


In [131]:

# accuracy of multilayer preceptron
MLP= accuracy_score(Y_test, y_predictMLP)
print("Accuracy of MLP is",MLP*100)
print(metrics.confusion_matrix(Y_test, y_predictMLP))

Accuracy of MLP is 93.75
[[7 1]
 [0 8]]


In [132]:
#accuracy of support vector machine
svm= accuracy_score(Y_test, y_predictsvm)
print("Accuracy of SVM is",svm*100)
print(metrics.confusion_matrix(Y_test, y_predictsvm))


Accuracy of SVM is 75.0
[[5 3]
 [1 7]]


In [151]:
#GaussianNB on 85  instances dataset
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, f1_score,precision_score,recall_score
classifier = GaussianNB()
classifier.fit(X_train, Y_train)
y_predictnaive=classifier.predict(X_test)

naive= accuracy_score(Y_test, y_predictnaive)
print("Accuracy of SVM is",naive*100)
print(metrics.confusion_matrix(Y_test, y_predictnaive))

fscore = f1_score(Y_test, y_predictnaive)
print("F1_score is:",fscore*100)
precisionscore=precision_score(Y_test, y_predictnaive)
print("precision is:",precisionscore*100)

recallscore=recall_score(Y_test, y_predictnaive)
print("recall is:",recallscore*100)

Accuracy of SVM is 76.47058823529412
[[4 4]
 [0 9]]
F1_score is: 81.81818181818181
precision is: 69.23076923076923
recall is: 100.0


In [134]:

from sklearn.tree import DecisionTreeClassifier


clf = DecisionTreeClassifier()
lpo = LeavePOut(p=2)
scores = cross_val_score(clf, X, Y, cv = lpo)
print("Cross validation scores of leave p out:",scores)
lpo_mean=scores.mean()
print("Average CV Score  of leave p out: ", lpo_mean)




split = ShuffleSplit(train_size=0.6, test_size=0.3, n_splits = 5)
scores_split = cross_val_score(clf, X, Y, cv = split)
print("Cross Validation Scores of monte carlo: ", scores_split)
print("Average CV Score of monte carlo: ", scores_split.mean())







Cross validation scores of leave p out: [1.  1.  1.  ... 1.  0.5 0.5]
Average CV Score  of leave p out:  0.9406645569620253
Cross Validation Scores of monte carlo:  [0.95833333 1.         0.875      1.         0.95833333]
Average CV Score of monte carlo:  0.9583333333333334
