In [3]:

#Q1. Compute the BoW model, TF model, and IDF model for each of the terms in the following three sentences. 
#Then calculate the TF.IDF values.
#S1 “sunshine state enjoy sunshine”
#S2 “brown fox jump high, brown fox run”
#S3 “sunshine state fox run fast”


from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer,TfidfVectorizer
texts = ["sunshine state enjoy sunshine","brown fox jump high, brown fox run","sunshine state fox run fast"]
bow_vectorizer = CountVectorizer()
bow= bow_vectorizer.fit_transform(texts)
names=bow_vectorizer.get_feature_names()
print(names)
print(bow.toarray())



['brown', 'enjoy', 'fast', 'fox', 'high', 'jump', 'run', 'state', 'sunshine']
[[0 1 0 0 0 0 0 1 2]
 [2 0 0 2 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 1]]


C:\python\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [4]:
tf_transformer = TfidfTransformer(use_idf=False).fit(bow)
tf = tf_transformer.transform(bow)
print(tf.toarray())


[[0.         0.40824829 0.         0.         0.         0.
  0.         0.40824829 0.81649658]
 [0.60302269 0.         0.         0.60302269 0.30151134 0.30151134
  0.30151134 0.         0.        ]
 [0.         0.         0.4472136  0.4472136  0.         0.
  0.4472136  0.4472136  0.4472136 ]]


=

In [7]:
idf_transformer = TfidfTransformer(smooth_idf=True,use_idf=True).fit(bow)
idf = idf_transformer.transform(bow)
print(idf.toarray())


[[0.         0.50689001 0.         0.         0.         0.
  0.         0.38550292 0.77100584]
 [0.67070313 0.         0.         0.51008702 0.33535157 0.33535157
  0.25504351 0.         0.        ]
 [0.         0.         0.54935123 0.41779577 0.         0.
  0.41779577 0.41779577 0.41779577]]


In [5]:
vectorizer = TfidfVectorizer()
tfidf = vectorizer.fit_transform(texts)
print(tfidf.toarray())


[[0.         0.50689001 0.         0.         0.         0.
  0.         0.38550292 0.77100584]
 [0.67070313 0.         0.         0.51008702 0.33535157 0.33535157
  0.25504351 0.         0.        ]
 [0.         0.         0.54935123 0.41779577 0.         0.
  0.41779577 0.41779577 0.41779577]]


In [ ]:
Q2. Compute the cosine similarity between S1 and S3.


In [10]:
import numpy as np
from numpy.linalg import norm
A = np.array([2,1,1,0,0,0])
B = np.array([1,1,0,1,1,1])
cosine = np.dot(A,B)/(norm(A)*norm(B))
print("Cosine Similarity:", cosine)

Cosine Similarity: 0.5477225575051661
